const INPUT_VALUE_CHANGED = 'INPUT_VALUE_CHANGED'
const FORM_STATE_CHANGED = 'FORM_STATE_CHANGED'
const LOGIN = 'LOGIN'
const REGISTER = 'REGISTER'

export { INPUT_VALUE_CHANGED, FORM_STATE_CHANGED, REGISTER, LOGIN }